OPM_SERIES_NAMES = {
    # 0000s — Miscellaneous Occupations
    "0006": "Correctional Officer",
    "0007": "Correctional Institution Admin",
    "0017": "Explosives Safety",
    "0018": "Safety & Occupational Health",
    "0019": "Safety Technician",
    "0020": "Community Planning",
    "0025": "Park Ranger",
    "0028": "Environmental Protection",
    "0030": "Sports Specialist",
    "0060": "Chaplain",
    "0080": "Security Administration",
    "0081": "Fire Protection",
    "0083": "Police",
    "0084": "Nuclear Materials Courier",
    "0085": "Security Guard",
    "0086": "Security Clerical",
    "0089": "Emergency Management",
    "0090": "Guide",
    "0099": "General Student Trainee",
    # 0100s — Social Science, Psychology, Welfare
    "0101": "Social Science",
    "0102": "Social Science Technician",
    "0105": "Social Insurance Admin",
    "0107": "Health Insurance Admin",
    "0110": "Economist",
    "0119": "Economics Assistant",
    "0130": "Foreign Affairs",
    "0131": "International Relations",
    "0132": "Intelligence",
    "0142": "Manpower Development",
    "0150": "Geography",
    "0170": "History",
    "0180": "Psychology",
    "0181": "Psychology Technician",
    "0182": "Psychology Aid",
    "0183": "Rehabilitation Counseling",
    "0185": "Social Work",
    "0186": "Social Services Aid",
    "0187": "Social Services",
    "0188": "Recreation Specialist",
    "0189": "Recreation Aid & Asst.",
    "0193": "Archaeology",
    "0199": "Social Science Student",
    # 0200s — Human Resources
    "0201": "Human Resources Mgmt.",
    "0203": "Human Resources Asst.",
    "0260": "Equal Employment Opportunity",
    # 0300s — General Administrative, Clerical, Office Services
    "0301": "Misc. Administration & Program",
    "0303": "Misc. Clerk & Asst.",
    "0304": "Information Receptionist",
    "0305": "Mail & File",
    "0306": "Government Info. (Publishing)",
    "0308": "Records Management",
    "0318": "Secretary",
    "0319": "Closed Microphone Reporting",
    "0326": "Office Automation Clerical",
    "0335": "Computer Operator",
    "0340": "Program Management",
    "0341": "Administrative Officer",
    "0342": "Support Services Admin.",
    "0343": "Program Analyst",
    "0344": "Management Clerical",
    "0346": "Logistics Management",
    "0350": "Equipment Operator",
    "0382": "Telephone Operating",
    "0390": "Telecommunications Processing",
    "0391": "Telecommunications",
    "0399": "Admin. & Office Support",
    # 0400s — Natural Resources Management and Biological Sciences
    "0401": "Biological Science",
    "0403": "Microbiology",
    "0404": "Biological Science Technician",
    "0415": "Toxicology",
    "0455": "Range Technician",
    "0456": "Plant Protection Technician",
    "0460": "Forestry",
    "0462": "Forestry Technician",
    "0482": "Fish Biology",
    "0499": "Biological Science Student",
    # 0500s — Accounting and Budget
    "0501": "Financial Administration",
    "0503": "Financial Clerical & Asst.",
    "0505": "Financial Management",
    "0510": "Accounting",
    "0511": "Auditing",
    "0525": "Accounting Technician",
    "0530": "Cash Processing",
    "0544": "Civilian Pay",
    "0545": "Military Pay",
    "0560": "Budget Analysis",
    "0570": "Financial Institution Examining",
    # 0600s — Medical, Hospital, Dental, and Public Health
    "0601": "General Health Science",
    "0602": "Medical Officer",
    "0603": "Physician Assistant",
    "0610": "Nurse",
    "0620": "Practical Nurse",
    "0621": "Nursing Assistant",
    "0622": "Medical Supply Aid & Technician",
    "0630": "Dietitian & Nutritionist",
    "0631": "Occupational Therapist",
    "0633": "Physical Therapist",
    "0635": "Kinesiotherapy",
    "0636": "Rehab. Therapy Asst.",
    "0638": "Recreation/Creative Arts Therapist",
    "0640": "Health Aid & Technician",
    "0642": "Nuclear Medicine Technician",
    "0644": "Medical Technologist",
    "0645": "Medical Technician",
    "0646": "Pathology Technician",
    "0647": "Diagnostic Radiologic Technologist",
    "0648": "Therapeutic Radiologic Technologist",
    "0649": "Medical Instrument Technician",
    "0660": "Pharmacist",
    "0661": "Pharmacy Technician",
    "0662": "Optometrist",
    "0665": "Speech Pathology",
    "0667": "Orthotist & Prosthetist",
    "0668": "Podiatrist",
    "0669": "Medical Records Admin.",
    "0670": "Health System Administration",
    "0671": "Health System Specialist",
    "0672": "Prosthetic Representative",
    "0673": "Hospital Housekeeping Mgmt.",
    "0675": "Medical Records Technician",
    "0679": "Medical Support Asst.",
    "0680": "Dental Officer",
    "0681": "Dental Assistant",
    "0682": "Dental Hygiene",
    "0683": "Dental Lab Technician",
    "0690": "Industrial Hygienist",
    "0699": "Medical & Health Student",
    "0701": "Veterinary Medical Science",
    "0704": "Animal Health Technician",
    # 0800s — Engineering and Architecture
    "0801": "General Engineering",
    "0802": "Engineering Technician",
    "0803": "Safety Engineering",
    "0804": "Fire Protection Engineering",
    "0806": "Materials Engineering",
    "0807": "Landscape Architecture",
    "0808": "Architecture",
    "0809": "Construction Control Technician",
    "0810": "Civil Engineering",
    "0819": "Environmental Engineering",
    "0830": "Mechanical Engineering",
    "0840": "Nuclear Engineering",
    "0850": "Electrical Engineering",
    "0854": "Computer Engineering",
    "0855": "Electronics Engineering",
    "0856": "Electronics Technician",
    "0858": "Biomedical Engineering",
    "0861": "Aerospace Engineering",
    "0871": "Naval Architecture",
    "0880": "Mining Engineering",
    "0893": "Chemical Engineering",
    "0896": "Industrial Engineering Technician",
    "0899": "Engineering Student",
    # 0900s — Legal and Kindred
    "0901": "General Legal",
    "0904": "Law Clerk",
    "0905": "General Attorney",
    "0950": "Paralegal Specialist",
    "0962": "Contact Representative",
    "0963": "Legal Instruments Examining",
    "0967": "Passport & Visa Examining",
    "0986": "Legal Clerk & Technician",
    "0996": "Veterans Claims Examining",
    "0999": "Legal Occupations Student",
    # 1000s — Information and Arts
    "1001": "General Arts & Information",
    "1008": "Interior Design",
    "1015": "Museum Curator",
    "1016": "Museum Specialist & Technician",
    "1020": "Illustrating",
    "1035": "Music Specialist",
    "1040": "Language Specialist",
    "1054": "Theater Specialist",
    "1071": "Audiovisual Production",
    "1084": "Visual Information",
    # 1100s — Business and Industry
    "1101": "Business & Industry",
    "1102": "Contracting",
    "1104": "Property Disposal",
    "1105": "Purchasing",
    "1106": "Procurement Clerical & Technician",
    "1109": "Grants Management",
    "1140": "Trade Specialist",
    "1144": "Commissary Management",
    "1145": "Agricultural Program Specialist",
    "1150": "Industrial Specialist",
    "1152": "Production Control",
    "1160": "Financial Analysis",
    "1170": "Realty",
    "1173": "Housing Management",
    "1176": "Building Management",
    "1199": "Business & Industry Student",
    "1220": "Patent Administration",
    "1222": "Patent Examiner",
    # 1300s — Physical Sciences
    "1301": "General Physical Science",
    "1306": "Health Physics",
    "1310": "Physics",
    "1311": "Physical Science Technician",
    "1316": "Hydrologic Technician",
    "1320": "Chemistry",
    "1330": "Astronomy & Space Science",
    "1340": "Meteorology",
    "1341": "Meteorological Technician",
    "1350": "Geology",
    "1361": "Navigational Information",
    "1397": "Document Analysis",
    # 1400s — Library and Archives
    "1410": "Librarian",
    "1411": "Library Technician",
    "1420": "Archivist",
    # 1500s — Mathematics and Statistics
    "1510": "Actuary",
    "1515": "Operations Research",
    "1529": "Mathematical Statistics",
    "1530": "Statistics",
    "1531": "Statistical Assistant",
    "1550": "Computer Science",
    "1560": "Data Science",
    # 1600s — Equipment, Facilities, and Services
    "1601": "Equipment, Facilities & Services",
    "1603": "Equipment Facilities Aid",
    "1630": "Cemetery Administration",
    "1640": "Facility Operations Services",
    "1654": "Printing Services",
    "1667": "Food Services",
    "1670": "Equipment Services",
    # 1700s — Education
    "1701": "General Education & Training",
    "1702": "Education Technician",
    "1710": "Education & Vocational Training",
    "1712": "Training Instruction",
    "1715": "Vocational Rehabilitation",
    "1730": "Education Research",
    "1740": "Education Services",
    "1750": "Instructional Systems",
    # 1800s — Investigation and Inspection
    "1801": "General Inspection & Compliance",
    "1802": "Compliance Inspection & Support",
    "1805": "Immigration Officer",
    "1810": "General Investigating",
    "1811": "Criminal Investigating",
    "1822": "Mine Safety & Health",
    "1825": "Aviation Safety",
    "1849": "Agricultural Resource Mgmt.",
    "1860": "Public Health Quarantine",
    "1862": "Consumer Safety Inspection",
    "1881": "Customs & Border Protection",
    "1889": "Import Specialist",
    "1894": "Grain Regulatory Specialist",
    "1895": "Agricultural Warehouse Inspection",
    "1896": "Border Patrol Agent",
    "1910": "Quality Assurance",
    # 2000s — Supply
    "2001": "General Supply",
    "2003": "Supply Program Management",
    "2005": "Supply Clerical & Technician",
    "2010": "Inventory Management",
    "2091": "Sales Store Clerical",
    # 2100s — Transportation
    "2101": "Transportation Specialist",
    "2102": "Transportation Clerk & Asst.",
    "2125": "Highway Safety Management",
    "2130": "Traffic Management",
    "2150": "Transportation Operations",
    "2151": "Dispatching",
    "2152": "Air Traffic Control",
    "2181": "Aircraft Operation",
    "2183": "Air Navigation",
    "2185": "Aircrew Technician",
    "2186": "Aerial Photography",
    # 2200s — Information Technology
    "2210": "IT Management",
    # 2500–2900s — Trades & Crafts (Electronics/Electrical)
    "2502": "Telecommunications Mechanic",
    "2504": "Electronic Mechanic",
    "2602": "Electronic Equipment Installation",
    "2604": "Electronic Industrial Controls Mechanic",
    "2606": "Electronic Measurement Equipment Mechanic",
    "2610": "Electronic Integrated Systems Mechanic",
    "2805": "Electrician",
    "2810": "Electrician (High Voltage)",
    "2892": "Cable Splicer",
    # 3000–3900s — Blue Collar Trades
    "3105": "Fabric Worker",
    "3306": "Ammunition Worker",
    "3378": "Liquid Fuels Handler",
    "3401": "Packing/Processing",
    "3414": "Woodworking",
    "3501": "Fabric Repair",
    "3502": "Textile Equipment Repair",
    "3566": "Custodial Work",
    "3602": "Fruit & Vegetable Worker",
    "3603": "Agricultural Aid",
    "3605": "Nursery Worker",
    "3703": "Welding",
    "3705": "Structural Iron Work",
    "3707": "Boilermaking",
    "3806": "Sheet Metal Work",
    # 4000–4900s — Blue Collar Trades (continued)
    "4010": "Plumbing",
    "4101": "Painting",
    "4102": "Painting (Naval)",
    "4104": "Sign Painting",
    "4204": "Pipefitting",
    "4206": "Plumbing",
    "4255": "Structural Systems Work",
    "4352": "Tile Setting",
    "4401": "Woodworking",
    "4406": "Boat Building & Repairing",
    "4601": "Bookbinding",
    "4602": "Bindery Worker",
    "4604": "Offset Lithography",
    "4605": "Letterpress Printing",
    "4607": "Offset Printing",
    "4701": "General Maintenance & Operations",
    "4741": "Engineering Equipment Operating",
    "4742": "Utility Systems Repairing",
    "4749": "Waste Water Treatment Operating",
    "4754": "Fuel Distribution System Mechanic",
    "4801": "General Equipment Mechanics",
    "4804": "Machinery Mechanic",
    "4805": "Industrial Equipment Mechanic",
    "4818": "Pumping Station Operating",
    "4819": "Stationary Engineering",
    "4840": "Tool & Equipment Mechanic",
    # 5000–5900s — Blue Collar (Misc., Explosives, Transportation)
    "5001": "Miscellaneous Occupations",
    "5003": "Mine Work",
    "5026": "Pest Controller",
    "5048": "Foundation & Structure Work",
    "5201": "Miscellaneous Warehousing",
    "5210": "Material Handler",
    "5301": "Misc. Fabricating & Processing",
    "5306": "Fabric Working",
    "5309": "Upholstering",
    "5318": "Textile Working",
    "5334": "Canvas Products Work",
    "5350": "Insulating",
    "5352": "Heat & Frost Insulating",
    "5378": "Asbestos Work",
    "5402": "Explosives Work",
    "5406": "Ammunition Examiner",
    "5407": "Liquid Fuels Handler",
    "5408": "Weapons Handler",
    "5409": "Ordnance Equipment Mechanic",
    "5413": "Mine Destruction Work",
    "5415": "Artillery Equipment Repairing",
    "5701": "Motor Vehicle Operating",
    "5703": "Motor Vehicle Mechanic",
    "5705": "Marine Machinery Mechanic",
    "5716": "Engineering Equipment Operating",
    "5729": "Tractor Operating",
    "5782": "Deck Operating",
    "5786": "Small Craft Operating",
    "5801": "Blue Collar Supervision",
    "5803": "Heavy Mobile Equipment Mechanic",
    "5806": "Aircraft Engine Mechanic",
    "5823": "Automotive Mechanic",
    # 6000–6900s — Ammunition & Ordnance / Drafting
    "6501": "Ammunition Handling",
    "6511": "Explosives Operating",
    "6601": "Ammunition Handler",
    "6605": "Cartridge & Propellant Device Mechanic",
    "6610": "Armament Repairing",
    "6641": "Ordnance Equipment Repairing",
    "6652": "Ammunition Examiner",
    "6901": "Land Surveying Aid & Technician",
    "6904": "Technical Drafting",
    "6907": "Engineering Aid",
    "6910": "Civil Engineering Drafting Aid",
    "6912": "Structural Drafting Aid",
    "6913": "Architectural Drafting Aid",
    "6914": "Electrical Drafting Aid",
    # 7000s — Food, Laundry, Custodial
    "7001": "Food Service Working",
    "7002": "Cooking",
    "7304": "Navy Cooks & Bakers",
    "7305": "Food Service Supervisor",
    "7401": "Laundry Working",
    "7404": "Dry Cleaning",
    "7405": "Pressing",
    "7407": "Laundry Machine Operating",
    "7408": "Laundry Aid",
    "7420": "Valet",
    "7603": "Steward",
    # 8000s — Electronics & Engineering Technician
    "8255": "Electro-optic Equipment Repairing",
    "8268": "Digital Computer Repairing",
    "8602": "Electrical Equipment Repairing",
    "8610": "Electronic Equipment Repairing",
    "8801": "Mechanical Engineering Technician",
    "8810": "Engineering Technician",
    "8840": "Technical Writing Aid",
    "8852": "Mechanical Drafting",
    "8862": "Civil Engineering Drafting Aid",
}


def classify_skill_type(skill: str) -> str:
    knowledge = {
        # Programming & Software
        "python", "java", "javascript", "typescript", "sql", "c++", "c#", "r programming",
        "aws", "azure", "gcp", "docker", "kubernetes", "linux", "react", "angular",
        "node.js", "postgresql", "mongodb", "git", "terraform", "devops", "scrum", "agile",
        "machine learning", "deep learning", "nlp", "artificial intelligence", "cloud computing",
        "data science", "data analysis", "computer vision", "autocad", "solidworks",
        "excel", "powerpoint", "tableau", "power bi", "sap", "sharepoint", "microsoft office",
        # Engineering & Physical Sciences
        "civil engineering", "mechanical engineering", "electrical engineering", "chemical engineering",
        "biomedical engineering", "aerospace engineering", "environmental engineering",
        "structural analysis", "geotechnical", "surveying", "construction management",
        # Life & Health Sciences
        "chemistry", "biology", "nursing", "pharmacy", "clinical", "healthcare", "public health",
        "epidemiology", "mental health", "patient care", "occupational therapy", "rehabilitation",
        "laboratory", "diagnostics", "forensics",
        # Finance, Law, Business
        "accounting", "auditing", "budgeting", "financial analysis", "financial reporting",
        "cost analysis", "risk management", "contracting", "procurement", "supply chain",
        "logistics", "inventory management", "warehouse management", "distribution",
        "program management", "project management", "policy analysis",
        "contract law", "administrative law", "legal research", "litigation",
        "regulatory compliance", "regulatory analysis", "compliance",
        # Security & Intelligence
        "cybersecurity", "network security", "information security", "intelligence analysis",
        "law enforcement", "surveillance", "investigation",
        # Other domains
        "statistics", "statistical analysis", "research methodology", "scientific writing",
        "data collection", "lean", "six sigma", "quality assurance",
        "employee relations", "labor relations", "recruitment", "workforce planning",
        "performance management", "strategic planning", "stakeholder engagement",
    }

    competence = {
        "communication", "leadership", "problem solving", "critical thinking", "teamwork",
        "writing", "public speaking", "negotiation", "analytical thinking", "decision making",
        "training", "change management", "scientific writing",
    }

    s = skill.lower()
    if s in knowledge:
        return "knowledge"
    if s in competence:
        return "competence"
    return "skill"


def get_series_name(series_code: str) -> str:
    return OPM_SERIES_NAMES.get(series_code, series_code)


ESCO_GROUP_TO_CATEGORY: dict[str, str] = {
    "information and communication technologies (icts)": "IT & Technology",
    "digital skills":                                    "IT & Technology",
    "engineering, manufacturing and construction":       "Engineering",
    "natural sciences, mathematics and statistics":      "Sciences & Analytics",
    "health and welfare":                                "Healthcare & Medicine",
    "social work and counselling":                       "Healthcare & Medicine",
    "business, administration and law":                  "Business & Finance",
    "accounting and taxation":                           "Business & Finance",
    "finance":                                           "Business & Finance",
    "logistics, distribution and transportation":        "Business & Finance",
    "procurement":                                       "Business & Finance",
    "management and administration":                     "Management & Leadership",
    "self-management skills and competences":            "Management & Leadership",
    "leadership skills and competences":                 "Management & Leadership",
    "leading others":                                    "Management & Leadership",
    "education":                                         "Management & Leadership",
    "human resources":                                   "HR & Workforce",
    "social and communication skills and competences":   "Soft Skills & Communication",
    "thinking skills and competences":                   "Soft Skills & Communication",
    "core skills and competences":                       "Soft Skills & Communication",
    "generic programmes and qualifications":             "Soft Skills & Communication",
    "personal skills and development":                   "Soft Skills & Communication",
    "literacy and numeracy":                             "Soft Skills & Communication",
    "life skills and competences":                       "Soft Skills & Communication",
    "arts and humanities":                               "Soft Skills & Communication",
    "services":                                          "Security & Public Safety",
    "security":                                          "Security & Public Safety",
    "law, police and corrections":                       "Security & Public Safety",
    "social sciences, journalism and information":       "Social Sciences & Policy",
    "agriculture, forestry, fisheries and veterinary":   "Sciences & Analytics",
    "physical and manual skills and competences":        "Engineering",
    "skills":                                            "Other",
}

LABEL_TO_CATEGORY: dict[str, str] = {
    # Management & Leadership
    "train employees":                              "Management & Leadership",
    "lean management":                              "Management & Leadership",
    "six sigma":                                    "Management & Leadership",
    "agile project management":                     "Management & Leadership",
    "manage stakeholders":                          "Management & Leadership",
    "apply change management":                      "Management & Leadership",
    "results-based management":                     "Management & Leadership",
    "project commissioning":                        "Management & Leadership",
    "knowledge management":                         "Management & Leadership",
    "office administration":                        "Management & Leadership",
    "application process":                          "Management & Leadership",
    "document management":                          "Management & Leadership",
    "assessment processes":                         "Management & Leadership",
    "manage emergency procedures":                  "Management & Leadership",
    "ensure compliance with construction project deadline": "Management & Leadership",
    "perform clerical duties":                      "Management & Leadership",
    "administer appointments":                      "Management & Leadership",
    "tutor students":                               "Management & Leadership",
    "manage time":                                  "Management & Leadership",
    "meet deadlines":                               "Management & Leadership",
    "assume responsibility":                        "Management & Leadership",
    "make decisions":                               "Management & Leadership",
    # HR & Workforce
    "recruit employees":                            "HR & Workforce",
    "workforce planning":                           "HR & Workforce",
    "human resource management":                    "HR & Workforce",
    "personnel management":                         "HR & Workforce",
    # Healthcare & Medicine
    "clinical skills":                              "Healthcare & Medicine",
    "provide patient care":                         "Healthcare & Medicine",
    "provide nursing care":                         "Healthcare & Medicine",
    "healthcare":                                   "Healthcare & Medicine",
    "mental health":                                "Healthcare & Medicine",
    "laboratory skills":                            "Healthcare & Medicine",
    "community medicine":                           "Healthcare & Medicine",
    "pharmacy":                                     "Healthcare & Medicine",
    "perform diagnostics":                          "Healthcare & Medicine",
    "apply techniques of occupational therapy":     "Healthcare & Medicine",
    "diagnostic radiology":                         "Healthcare & Medicine",
    "oral surgery":                                 "Healthcare & Medicine",
    "stomatology":                                  "Healthcare & Medicine",
    "primary care":                                 "Healthcare & Medicine",
    "medical terminology":                          "Healthcare & Medicine",
    "occupational health":                          "Healthcare & Medicine",
    # Legal & Compliance
    "ensure compliance with regulations":           "Legal & Compliance",
    "contract management":                          "Legal & Compliance",
    "audit compliance":                             "Legal & Compliance",
    "litigation":                                   "Legal & Compliance",
    "regulatory analysis":                          "Legal & Compliance",
    "regulatory compliance":                        "Legal & Compliance",
    "employment law":                               "Legal & Compliance",
    "manage contracts":                             "Legal & Compliance",
    "road traffic laws":                            "Legal & Compliance",
    # IT & Technology
    "amazon web services":                          "IT & Technology",
    "microsoft azure":                              "IT & Technology",
    "google cloud platform":                        "IT & Technology",
    "docker":                                       "IT & Technology",
    "kubernetes":                                   "IT & Technology",
    "terraform":                                    "IT & Technology",
    "react":                                        "IT & Technology",
    "node.js":                                      "IT & Technology",
    "mongodb":                                      "IT & Technology",
    "postgresql":                                   "IT & Technology",
    "tableau":                                      "IT & Technology",
    "power bi":                                     "IT & Technology",
    "linux":                                        "IT & Technology",
    "git":                                          "IT & Technology",
    "sharepoint":                                   "IT & Technology",
    "sap":                                          "IT & Technology",
    "principles of artificial intelligence":        "IT & Technology",
    "cloud technologies":                           "IT & Technology",
    "natural language processing":                  "IT & Technology",
    "use spreadsheets software":                    "IT & Technology",
    "use microsoft office":                         "IT & Technology",
    "air traffic management":                       "IT & Technology",
    "desktop publishing":                           "IT & Technology",
    "control systems":                              "IT & Technology",
    "office equipment":                             "IT & Technology",
    "computer technology":                          "IT & Technology",
    "computer science":                             "IT & Technology",
    "support ict system users":                     "IT & Technology",
    # Business & Finance
    "distribution management":                      "Business & Finance",
    "budget management":                            "Business & Finance",
    "inventory management rules":                   "Business & Finance",
    "e-procurement":                                "Business & Finance",
    "qualitative risk analysis techniques":         "Business & Finance",
    "financial reporting":                          "Business & Finance",
    "supply machine":                               "Business & Finance",
    "financial management":                         "Business & Finance",
    "sales activities":                             "Business & Finance",
    "business knowledge":                           "Business & Finance",
    "exert expenditure control":                    "Business & Finance",
    "process payments":                             "Business & Finance",
    "operate cash register":                        "Business & Finance",
    "stock shelves":                                "Business & Finance",
    "sell tickets":                                 "Business & Finance",
    "unload cargo":                                 "Business & Finance",
    # Security & Public Safety
    "conduct investigations":                       "Security & Public Safety",
    "conduct surveillance":                         "Security & Public Safety",
    "intelligence analysis":                        "Security & Public Safety",
    "law enforcement":                              "Security & Public Safety",
    "forensic science":                             "Security & Public Safety",
    "security clearance":                           "Security & Public Safety",
    "prevent theft":                                "Security & Public Safety",
    "manage emergency procedures":                  "Security & Public Safety",
    "first response":                               "Security & Public Safety",
    "personal protective equipment":                "Security & Public Safety",
    "alarm systems":                                "Security & Public Safety",
    "health and safety in the workplace":           "Security & Public Safety",
    # Sciences & Analytics
    "environmental assessment":                     "Sciences & Analytics",
    "scientific writing":                           "Sciences & Analytics",
    "laboratory skills":                            "Sciences & Analytics",
    "collect data":                                 "Sciences & Analytics",
    "conservation techniques":                      "Sciences & Analytics",
    "waste management":                             "Sciences & Analytics",
    "scientific research methodology":              "Sciences & Analytics",
    "manage quantitative data":                     "Sciences & Analytics",
    "physics":                                      "Sciences & Analytics",
    # Soft Skills & Communication
    "write reports":                                "Soft Skills & Communication",
    "public speaking":                              "Soft Skills & Communication",
    "provide technical documentation":              "Soft Skills & Communication",
    "customer service":                             "Soft Skills & Communication",
    "use presentation software":                    "Soft Skills & Communication",
    "deal with public":                             "Soft Skills & Communication",
    "deliver outstanding service":                  "Soft Skills & Communication",
    "make reservations":                            "Soft Skills & Communication",
    "file documents":                               "Soft Skills & Communication",
    "fill out forms":                               "Soft Skills & Communication",
    "provide information":                          "Soft Skills & Communication",
    "assist customers":                             "Soft Skills & Communication",
    "cope with stress":                             "Soft Skills & Communication",
    "exercise patience":                            "Soft Skills & Communication",
    "think analytically":                           "Soft Skills & Communication",
    "write english":                                "Soft Skills & Communication",
    "interact verbally in english":                 "Soft Skills & Communication",
    "public relations":                             "Soft Skills & Communication",
    # Engineering
    "autocad":                                      "Engineering",
    "solidworks":                                   "Engineering",
    "geotechnical engineering":                     "Engineering",
    "read engineering drawings":                    "Engineering",
    "design metal components":                      "Engineering",
    "plan construction of houses":                  "Engineering",
    "maintain equipment":                           "Engineering",
    "carry objects":                                "Engineering",
    "use hand tools":                               "Engineering",
    "maintain ground":                              "Engineering",
    "hang wallpaper":                               "Engineering",
    "mechanical systems":                           "Engineering",
    "electronics":                                  "Engineering",
    "types of electronics":                         "Engineering",
    # Social Sciences & Policy
    "museology":                                    "Social Sciences & Policy",
    "public administration":                        "Social Sciences & Policy",
    # Labour Relations (cross-category)
    "labour relations":                             "HR & Workforce",
    "network security":                             "IT & Technology",
}

_CHAIN_KEYWORDS: list[tuple[list[str], str]] = [
    (["ict", "digital", "computing", "software", "data", "technology"],  "IT & Technology"),
    (["health", "medical", "nursing", "care", "welfare"],                "Healthcare & Medicine"),
    (["engineer", "construct", "manufactur", "mechanical"],              "Engineering"),
    (["law", "legal", "compli", "regulation"],                           "Legal & Compliance"),
    (["manag", "leadership", "administr", "organis"],                    "Management & Leadership"),
    (["science", "research", "mathemat", "statist", "analyt"],           "Sciences & Analytics"),
    (["communic", "social", "personal", "literacy"],                     "Soft Skills & Communication"),
    (["secur", "police", "safety", "protect", "investigat"],             "Security & Public Safety"),
    (["finance", "account", "budget", "econom", "business"],             "Business & Finance"),
    (["human resource", "recruit", "workforce"],                         "HR & Workforce"),
]


def get_skill_category(label: str, esco_uri: str | None = None,
                       esco_chain: list[str] | None = None) -> str:
    key = label.lower().strip()

    if key in LABEL_TO_CATEGORY:
        return LABEL_TO_CATEGORY[key]

    if esco_chain:
        for step in esco_chain:
            cat = ESCO_GROUP_TO_CATEGORY.get(step.lower())
            if cat:
                return cat
        chain_str = " ".join(esco_chain).lower()
        for keywords, cat in _CHAIN_KEYWORDS:
            if any(kw in chain_str for kw in keywords):
                return cat

    return "Other"
